### ISSUE TITLE
 The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by NuLL3rr0r** [easyCZ/logrotate#1]
Sample code, running on Microsoft Windows, which panics:

```go
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/easyCZ/logrotate"
	jww "github.com/spf13/jwalterweatherman"
)

func main() {
	jww.SetLogThreshold(jww.LevelTrace)
	jww.SetStdoutThreshold(jww.LevelTrace)

	writer, err := logrotate.New(jww.TRACE, logrotate.Options{
		// Where should the writer be outputting files?
		// If the directory does not exist, it will be created.
		// Required.
		Directory: getExecutableDir(),
		// What is the maximum size of each file?
		// Optional. Use 0 for unlimited.
		MaximumFileSize: 1024 * 1024 * 1024,
		// How often should a new file be created, based on time?
		// Optional. Use 0 to disable time based log rotation.
		MaximumLifetime: time.Hour,
		// How would you like to name your files?
		// Invoked each time a new file is being created.
		FileNameFunc: logrotate.DefaultFilenameFunc,
	})
	if err != nil {
		fatal(err)
	}
	jww.SetLogOutput(writer)

	jww.INFO.Println("This is a test info log.")
	jww.TRACE.Println("This is a test trace log.")
	jww.ERROR.Println("This is a test error log.")
	jww.FATAL.Println("This is a test fatal log.")

	// Ensure all messages are flushed to files before exiting
	err = writer.Close()
	if err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	jww.FATAL.Println(err)
	fmt.Print("Press the Enter key to continue...")
	bufio.NewReader(os.Stdin).ReadBytes('\n')
	os.Exit(1)
}

func getExecutableDir() string {
	ex, err := os.Executable()
	if err != nil {
		jww.FATAL.Println(err)
		panic("Failed to find the executable directory!")
	}
	dir := filepath.Dir(ex)
	return dir
}
```

Though, [on the playground](https://play.golang.org/p/IwzV2cGcXgv), it works.

On Microsoft Windows it fails with:

```
3 Failed to create log file failed to create new file at D:\2021-07-22T14:23:43Z-spD.log: open D:\2021-07-22T14:23:43Z-spD.log: The filename, directory name, or volume label syntax is incorrect.
TRACE 2021/07/22 16:23:43 Failed to rotate log file failed to create new file at D:\2021-07-22T14:23:43Z-dry.log: open D:\2021-07-22T14:23:43Z-dry.log: The filename, directory name, or volume label syntax is incorrect.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xebbd79]

goroutine 6 [running]:
bufio.(*Writer).Available(...)
        C:/Program Files/Go/src/bufio/bufio.go:624
bufio.(*Writer).Write(0x0, 0xc000010200, 0x32, 0x40, 0xe10, 0x0, 0x1)
        C:/Program Files/Go/src/bufio/bufio.go:634 +0x79
github.com/easyCZ/logrotate.(*Writer).listen(0xc0000a6000)
        D:/SOME/PATH/vendor/github.com/easyCZ/logrotate/writer.go:139 +0x13b
created by github.com/easyCZ/logrotate.New
        D:/SOME/PATH/vendor/github.com/easyCZ/logrotate/writer.go:206 +0x199
```

**Comment by easyCZ** [comment]
Hey @NuLL3rr0r,

Thanks for raising the Issue. I've had a chance to look at this briefly but struggling to reproduce without a Windows machine. I'll see if I can get my hands on a VM to test this out.

From a cursory search, this looks like interaction between the writer and the OS Filesystem but I don't really have any more insight than that at this point.

If you do have access to a Windows machine, running it in debug mode and stepping through it could shed more light.

**Comment by mpsq** [comment]
Your error is:

```
Failed to create log file failed to create new file at D:\2021-07-22T14:23:43Z-spD.log: open D:\2021-07-22T14:23:43Z-spD.log: The filename, directory name, or volume label syntax is incorrect.
```

According to the [official documentation](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file), Windows has (amongst others) those restrictions for file names:

```
Use any character in the current code page for a name, including Unicode characters
and characters in the extended character set (128–255), except for the following:

The following reserved characters:
        < (less than)
        > (greater than)
        : (colon)
        " (double quote)
        / (forward slash)
        \ (backslash)
        | (vertical bar or pipe)
        ? (question mark)
        * (asterisk)
...
```

So `2021-07-22T14:23:43Z-spD.log` is not valid.

**Comment by easyCZ** [comment]
Nice @mpsq. This format is generated by the `logrotate.DefaultFilenameFunc`. You can try supplying a custom format.

I'll create a fix to use filename scheme compliant with Windows and will cut a new version of this library.

**Comment by NuLL3rr0r** [comment]
Thank you! I ended up using (natefinch/lumberjack)[https://github.com/natefinch/lumberjack], which is very similar with some other features.
